### ISSUE TITLE
Refactoring Forte Store (embed or iframe handle)

### ISSUE THREAD

**Issue by getsolaris** [team-crescendo/laravel-forte-api#101]
#108

**Comment by HyungJu** [comment]
Xsolla Paystation과 Forte 도메인이 다른 관계로 embed와 iframe에 직접 접근은 불가능 한것으로 확인했습니다
Xsolla에서 제공하는 이벤트 중 **향후 아이템 구매 시 확인 화면 비활성화 선택 후 버튼 클릭시** 발생하는 이벤트는 없습니다.

다만 해당 옵션을 비활성화 할 수 있는 페이지 띄우는 커맨드를 Postmessage로 전달해주면 되는것 같긴 한데
제 쪽에서 테스트를 해보니까 안되는듯 하네요 ㅋㅋㅋㅋㅋ..

`$("iframe").get(0).contentWindow.postMessage("{'command':'open-useraccount', 'data': ''}")`

어떻게 하는게 좋을까요 ? @getsolaris @kang-heewon

**Comment by getsolaris** [comment]
Xsolla Paystation 에서 '구입' 버튼을 클릭 하면 Forte Store 에서 event 를 띄우는 방식은 어떠신가요 ?

```js
document.querySelector("body > ui-view > x-desktop-ctrl > div > fixed-layout > fixed-layout-content > div > x-desktop-virtual-item-state > div > x-desktop-virtual-item-vertical-state > div > section > fixed-layout-scrollable.virtual-item-content > div > div > x-virtual-item-list > div > x-virtual-item-grid-option > div > div.virtual-item-option-wrapper > div.virtual-item-option-footer > div > div > div.virtual-item-option-button > button")
```

**Comment by HyungJu** [comment]
오잉 그게 가능한가요? 버튼 click 이벤트로 Alert 창을 띄워보려고 했는데 이벤트를 잡는게 아예 불가능해 보이던데요

**Comment by getsolaris** [comment]
아 ㅋㅋ 그렇겠네요
잘못 봤네요

프론트단에서 처리 가능한 더 좋은 방법이 있을련지 ..

**Comment by HyungJu** [comment]
그러게요 ... 이전에는 청약철회 기능이 있었던것 같은데 사라진 이유가 있나요?

**Comment by getsolaris** [comment]
https://github.com/team-crescendo/laravel-forte-api/blob/master/app/Http/Controllers/UserItemController.php

master 브랜치 확인 하시면 `withdraw` 메소드 확인이 가능합니다.

현재 청약철회 이슈때문에 잠시 홀드 해뒀어요.. 
이슈 픽스를 진행 해야하는데 회사일 때문에 바빠 진행을 못하고 있네요..
