### ISSUE TITLE
GuzzleHttp\Exception\ServerException Server error: `POST https://discordapp.com/api/oauth2/token` resulted in a `500 Internal Server Error`

### ISSUE THREAD

**Issue by getsolaris** [team-crescendo/laravel-forte-api#118]
GuzzleHttp\Exception\ServerException
Server error: `POST https://discordapp.com/api/oauth2/token` resulted in a `500 Internal Server Error` response:
```json
{"message": "500: Internal Server Error", "code": 0}
```

**Comment by HyungJu** [comment]
디코 로그인 페이지에서 **거절** -> 그대로 뒤로가기 후 **승인** 하면 500에러가 재현되는걸 확인했는데 혹시 이거랑 연관이 있을까용

**Comment by getsolaris** [comment]
https://forte.team-crescendo.me/login/discord/callback?error=access_denied&error_description=The+resource+owner+or+authorization+server+denied+the+request

callback 부분에서 error 가 넘어오게 된다면 exception 이 필요할 것 같네요

**Comment by getsolaris** [comment]
@HyungJu 우선 이 부분은 천천히 짚고 나가도 될 것 같아요 !

**Comment by HyungJu** [comment]
네 알겠습니다 :)
