### ISSUE TITLE
staff 포인트 자동 지급 개편

### ISSUE THREAD

**Issue by getsolaris** [team-crescendo/laravel-forte-api#127]

**Comment by HyungJu** [comment]
![image](https://user-images.githubusercontent.com/9509286/86372189-d1ec0180-bcbc-11ea-8b85-84932e475716.png)
??

**Comment by getsolaris** [comment]
@HyungJu 해당 로직이 정상적으로 작동되나 확인 한번 부탁드릴게요.

**Comment by HyungJu** [comment]
넹 알겠습니다
