### ISSUE TITLE
상점에서 포인트로 구매한 아이템의 Receipt가 이상하게 찍힙니다

### ISSUE THREAD

**Issue by GBS-Skile** [team-crescendo/laravel-forte-api#198]
### 이슈 설명

사용자가 포르테 상점에서 포인트로 구매한 아이템의 Receipt는 기획 의도상 다음 양식을 따라야 합니다.

1. `about_cash` 필드는 영수증이 실제 현금과 관계있는지 확인하기 위한 boolean 필드이기 때문에,
**"포인트"로 구매한 경우 `about_cash`가 0이 되어야 합니다.**
1. `points_old` 는 구매 전 보유 포인트, `points_new` 는 구매 후 보유 포인트입니다.
**"포인트"로 구매한 경우 상식적으로 `points_new`는 `points_old` 보다 아이템 가격만큼 작은 값이어야 합니다.**

근데 DB에 찍히는 Receipt 관련 레코드를 보니 현금 전용 아이템이 아니더라도 `about_cash`가 1로 찍히고, `points_new`와 `points_old` 필드가 같은 값을 가지고 있습니다.

### 요청 URL 
- POST /api/v1/xsolla

### 요청 JSON

사용자가 아이템을 구매하면 대충 이런 느낌의 Request Body가 같이 딸려옵니다

```json
{
    "notification_type": "user_balance_operation",
    "settings": {
        "project_id": <숫자>,
        "merchant_id": <숫자>
    },
    "id_operation": <숫자>,
    "operation_type": "inGamePurchase",
    "user": {
        "id": "<숫자>",
        "name": "<닉네임>",
        "country": "KR"
    },
    "items_operation_type": "add",
    "items": [
        {
            "sku": "<SKU>",
            "amount": 1
        }
    ],
    "virtual_currency_balance": {
        "old_value": <숫자>,
        "new_value": <숫자>,
        "diff": <숫자>
    }
}
```

### 부가 설명

제가 봤을때는 `UserItem.php#createUserReceipt()` 함수의 논리가 잘못되어서 그런거같습니다.
어차피 지금은 엑솔라 웹훅을 통해서만 아이템 구매를 처리하고 있어서 `$token == 'xsolla'` 조건은 사실상 의미가 없고, `$token == 'xsolla'` 더라도 유저가 보유하고 있는 포인트는 깎이는 게 맞습니다.

`about_cash` 는 `$item->price` 가 0인지 아닌지에 따라 구분해서 넣으면 될거같습니다

**Comment by HyungJu** [comment]
아마 해결한것 같습니다 •••
