### ISSUE TITLE
User 필드 중복에 대한 응답이 POST ~ PUT 사이에 일관성이 없음

### ISSUE THREAD

**Issue by GBS-Skile** [team-crescendo/laravel-forte-api#22]
**Describe the bug**
POST /users 요청을 보낼 때는 user_name, email 에 대한 중복 검사를 하지 않습니다.
PUT /users 요청을 보낼 때는 user_name, email 에 대한 다른 DB에 중복된 필드를 제거한 상태로 요청을 수행합니다.
두 요청에 대한 반응이 일관적이지 않습니다.

**To Reproduce**
* *POST /users* name a, email b@example.com (id 1)
* *POST /users* name a, email b@example.com (id 2, 정상적으로 생성됨)
* *PUT /users* id 1, name b (정상 작동)
* *PUT /users* id 1, name a (success라고 반응하지만 name이 b -> a로 바뀌지 않음)

**Expected behavior**
엑솔라 DB에서도 user_name과 email에 대한 중복을 검사하지 않고, User를 구분하는 데는 discord id나 pk를 사용하지 user_name이나 email로 user를 찾는 경우가 없기 때문에 PUT 요청에서 중복을 제거하는 기능을 빼면 될 것 같습니다.

또는 POST 요청에서 user_name, email에 대한 중복 체크를 추가하셔도 됩니다.

**Comment by getsolaris** [comment]
중복 검사에 대해서는 #21 에서 처리 했으며
PUT 에 대해서는 user_id 만 필수로 받으며 그외 필드는 변경할 필드만 업데이트를 하도록 되어있습니다.
