### ISSUE TITLE
FORTE API v2 서비스를 위한 리팩토링

### ISSUE THREAD

**Issue by getsolaris** [team-crescendo/laravel-forte-api#98]
## Controllers
- [x] CleanLogController @HyungJu 
- [x] ClientController @HyungJu 
- [x] DiscordNotificationController @getsolaris 
- [x] ItemController @getsolaris  
- [x] PointController @getsolaris  
- [x] ReceiptController @getsolaris 
- [x] UserController @getsolaris 
- [x] UserItemController @getsolaris  
- [x] XsollaWebhookController @getsolaris 

## Services
- [x] BackupService @HyungJu 
- [x] ItemService @getsolaris 
- [x] PointService @getsolaris
- [x] ReceiptService @getsolaris 
- [x] UserItemService @getsolaris 
- [x] UserService @getsolaris 
- [x] XsollaAPIService @getsolaris 
- [x] XsollaWebookService @getsolaris 

## Models
각 컨트롤러, 서비스에 할당된 모델 리팩토링하기
ex) ItemController -> Item

리팩토링 과정은 브랜치 하나씩 생성하여 진행 -> PR

**Comment by HyungJu** [comment]
@getsolaris `DiscordNotificationController`41번째 줄 Discord 메시지 보내는 부분에서 send 첫번째 파라미터에 `in_array(self::CHANNEL_ERROR, self::DISCORD_CHANNELS)` 이 부분 혹시 어떤 특별한 의미가 있을까요?

확인해 보니 채널 ID가 들어가는 곳인데 in_array는 boolean을 리턴하다보니 ..

**Comment by getsolaris** [comment]
@HyungJu 그 부분 수정 부탁드릴게요
